In [1]:
import pandas as pd
import numpy as np

In [2]:
#step1 collect data
x  = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0],[1],[1],[0]])
print ("x=\n {}\n\ny=\n{}".format(x,y))

x=
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

y=
[[0]
 [1]
 [1]
 [0]]


In [3]:
#step2 build model
num_epochs = 150000
#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print ("syn0= \n{}\n\nsyn1=\n{}".format(syn0,syn1))

syn0= 
[[ 0.95103555 -0.31660376  0.16581839  0.57239062]
 [-0.80289735 -0.26210493 -0.38367053  0.37091851]
 [ 0.26287691 -0.88442575 -0.03023311 -0.0854063 ]]

syn1=
[[0.44499754]
 [0.0165374 ]
 [0.70264428]
 [0.07349569]]


![](https://cdn-images-1.medium.com/max/1200/1*Vo7UFksa_8Ne5HcfEzHNWQ.png)
Other activation functions: https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6

In [4]:
def sig_moid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [6]:
#Step 3 Train Model

for j in range(num_epochs):
    #feed forward through layers 0,1, and 2
    k0 = x
    k1 = sig_moid(np.dot(k0, syn0))
    k2 = sig_moid(np.dot(k1, syn1))
    #how much did we miss the target value?
    k2_error = y - k2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(k2_error))))
    
    #in what direction is the target value?
    k2_delta = k2_error*sig_moid(k2, deriv=True)
    
    #how much did each k1 value contribute to k2 error
    k1_error = k2_delta.dot(syn1.T)
    
    k1_delta= k1_error * sig_moid(k1,deriv=True)
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)

Error:0.5009510292349898
Error:0.010817861798292305
Error:0.007442627984403794
Error:0.006008190193934582
Error:0.005168769040784508
Error:0.00460225283259651
Error:0.004187250261468756
Error:0.003866535385672995
Error:0.0036091587608803525
Error:0.003396735116801672
Error:0.003217568383045952
Error:0.003063818090165331
Error:0.002930006457807619
Error:0.002812175913181697
Error:0.0027073867442787124


In [7]:
k0

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [8]:
k1

array([[9.14086969e-01, 2.64369883e-01, 9.73214976e-02, 5.83588743e-01],
       [2.76533252e-02, 3.06589539e-02, 5.98761419e-05, 9.80661828e-01],
       [9.99963326e-01, 3.28351932e-02, 9.60127425e-01, 9.76706638e-01],
       [9.86465045e-01, 2.97900783e-03, 1.31974188e-02, 9.99341338e-01]])

In [9]:
k2

array([[0.00119541],
       [0.99687631],
       [0.99737833],
       [0.00351288]])